### PR TITLE
Reload Inline Styles from HTML into the Editor

### PR DESCRIPTION
**Pull request by stagfoo**
Hey, So I noticed that you can't reload coloured text and but just removing the # it would be pretty easy to match the inline-styles with the colours from the picker

### CODE REVIEW

**Comment by StevenIseki** [comment]
Hi, thanks for this pull request it is some nice work. It works well with the pr you set up for [ld-color-picker](https://github.com/StevenIseki/ld-color-picker/pull/1). Only one issue I can see is that editorStateToHtml is not working for me, whereas editorStateFromHtml works nicely. If you can fix that up I will merge this all in and publish a new version. Once again thanks for your help 👍 

As shown in the screenshot below where I log `(editorStateToHtml(editorState)` in onChange of `Example.js`: 

screen shot 2017-02-05 at 8 58 18 pm

**Comment by stagfoo** [comment]
Oh ok I might have missed a commit, I'll look at it tonight and git it cleaned up :)

**Comment by stagfoo** [comment]
So yer i had forgot the convert.js part but im glad a revisited it because, i have updated it to work with dropcap and theoretically any style in the stylemap should now convert to inline styles. 
The quote doesn't seem to be in the style map?

**Comment by stagfoo** [comment]
I see the issue with quotes. its a block element and my conversion is only for inline at the moment

**Comment by StevenIseki** [comment]
That sounds awesome, thanks @stagfoo I will definitely test this out and hopefully merge/publish it today

**Pull request merged**
